[package]
name = "img-sort"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
globwalk = "0.9.1"
kamadak-exif = "0.5.5"


[dev-dependencies]
image = "0.25.1"
tempfile = "3.10.1"